[package]
name = "fee-burn-engine"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true, default-features = false }
soroban-token-sdk = { version = "20.0.0", default-features = false }

[dev-dependencies]
soroban-sdk = { workspace = true, default-features = false, features = ["testutils"] }
