[package]
name = "price-oracle"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true, default-features = false }
hex = "0.4.3"

[dev-dependencies]
soroban-sdk = { workspace = true, default-features = false, features = ["testutils"] }