[package]
name = "staking-pool"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
soroban-sdk = { version = "=20.0.0", default-features = false, features = ["testutils"] }

[dev-dependencies]
soroban-sdk = { version = "=20.0.0", default-features = false, features = ["testutils"] }

[lib]
crate-type = ["cdylib", "rlib"]
